title: "淳文字。"
title_separator: "|"
description: "CHUNWENZI · Journal of Words, Memories & Human Stories"
url: "https://maochunweitw.github.io"
baseurl: ""
markdown: kramdown
permalink: /posts/:title/
timezone: Asia/Taipei
